parameters:
    sidus_data_class: FabricDatabase\EAVModelBundle\Entity\Data
    sidus_value_class: FabricDatabase\EAVModelBundle\Entity\Value

    color.choices:
        Blanc: 'ffffff'
        Jaune: 'ffd700'
        Orange: 'd2691e'
        Rose: 'ff69b4'
        Rouge: 'dc143c'
        Vert: '008000'
        Bleu: '0000cd'
        Cyan: '66ccff'
        Violet: '4b0082'
        Marron: '8b4513'
        Gris: '808080'
        Beige: 'd2b48c'
        Noir: '000000'

sidus_eav_model:
    data_class: '%sidus_data_class%'
    value_class: '%sidus_value_class%'
    serializer_enabled: true

clever_age_eav_manager_user:
    mailer:
        company: Client Company
        from_email: no-reply@client-company.com
        from_name: Client

imports:
    - { resource: '@CleverAgeEAVManagerAdminBundle/Resources/config/base_config.yml' }
    - { resource: admin.yml }
    - { resource: eav_datagrid.yml }

    # Model configuration, order of files matters
    - { resource: model/Fabric.yml }
    - { resource: model/User.yml }

    - { resource: model/Options/FabricType.yml }
    - { resource: model/Options/Material.yml }
    - { resource: model/Options/Pattern.yml }
    - { resource: model/Options/Property.yml }
    - { resource: model/Options/SizeClass.yml }
    - { resource: model/Options/Storage.yml }
    - { resource: model/Options/Yardage.yml }

    - { resource: model/Referentials/Merchant.yml }
