sidus_eav_model:
    families:
        Storage:
            attributeAsLabel: label
#            attributeAsIdentifier: code
            attributes:
#                code:
#                    type: string_identifier
                label:
                    required: true
