sidus_eav_model:
    families:
        Merchant:
            attributeAsLabel: label
            attributes:
                label:
                    required: true
                website:
                    validation_rules:
                        - Url: ~
