# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

clever_age_eav_manager_user:
    mailer:
        company: Fabric Database
        from_email: '%mailer_from_email%'
        from_name: '%mailer_from_name%'
