parameters:
    sidus_data_class: FabricDatabase\EAVModelBundle\Entity\Data
    sidus_value_class: FabricDatabase\EAVModelBundle\Entity\Value

    locale: fr

    export.button:
        form_type: Symfony\Component\Form\Extension\Core\Type\SubmitType
        label: admin.action.export.label
        icon: upload
