imports:
    - { resource: parameters.yml }
    - { resource: parameters/* }
    - { resource: application/* }

    - { resource: '@CleverAgeEAVManagerAdminBundle/Resources/config/base_config.yml' }
    - { resource: admin/* }
    - { resource: datagrid/* }
    - { resource: model/* }
