version: '2'

services:
    www:
        build: www
        working_dir: /var/www/current
        depends_on:
            - mysql
            - mailcatcher
        ports:
            - ${WWW_PORT}:80
        volumes:
            - ${APP_DIR}:/var/www/current
            - ./www/nginx/sites-available/:/etc/nginx/sites-available/
            - ./www/supervisor/:/etc/supervisor/conf.d/
            - ${SSH_AUTH_SOCK}:/ssh-agent
        environment:
            SF_DATABASE_HOST: mysql
            SF_DATABASE_PORT: 3306
            SF_DATABASE_NAME: ${MYSQL_DATABASE}
            SF_DATABASE_USER: ${MYSQL_USER}
            SF_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
            SF_MAILER_TRANSPORT: smtp
            SF_MAILER_HOST: 'mailcatcher:1025'
            SF_MAILER_USER: '~'
            SF_MAILER_PASSWORD: '~'
            SF_SECRET: ${SF_SECRET}
            PHP_IDE_CONFIG: 'serverName=fabrics-cli'

    mysql:
        image: mariadb
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'true'
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    mailcatcher:
        image: zolweb/docker-mailcatcher:latest
        ports:
            - ${MAILCATCHER_PORT}:1080

    deploy:
        build: capistrano
        volumes:
            - ${APP_DIR}/deploy:/source
            - ${SSH_AUTH_SOCK}:/ssh-agent
        environment:
            SSH_AUTH_SOCK: '/ssh-agent'
