sidus_data_grid:
    configurations:
        storage:
            query_handler:
                provider: sidus.eav
                options:
                    family: Storage
                sortable:
                    - id
                    - createdAt
                    - updatedAt
                filters: []
            columns:
                id:
                    label: '#'
                label:
                    template: '%clickable.template%'
                createdAt: ~
                updatedAt: ~
                actions:
                    template: '%eav_datagrid.actions%'
            actions:
                create: '%create.button%'
            reset_button:
                attr:
                    data-target: tg_center
